name: Generate Private Key & CSR Status

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python status/checkpvtcsr.py

      - name: Update status badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: <your-gist-id>
          filename: online-status.json
          label: Online Status
          message: Running
          color: green

      - name: Update status badge (if failed)
        uses: schneegans/dynamic-badges-action@v1.1.0
        if: ${{ failure() }}
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: <your-gist-id>
          filename: online-status.json
          label: Online Status
          message: Failed
          color: red
